/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CalendarIntent,  RequestType } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CalendarIntent {
      /**
       * Whether this message requires a calendar action
       */
      action_needed?: boolean | null
      /**
       * Type of calendar request
       */
      request_type?: types.RequestType | null
      /**
       * Name of person who originally requested the meeting
       */
      requestor?: string | null
      /**
       * What time slots are suggested
       */
      time_slots_requested?: string | null
      /**
       * How long is being requested (e.g., "30 mins", "1 hour", "2 hours")
       */
      meeting_duration?: string | null
      /**
       * The earliest datetime being considered for the meeting formatted as YYYY-mm-dd hh:mm
       */
      timerange_start?: string | null
      /**
       * The latest datetime being considered for the meeting formatted as YYYY-mm-dd hh:mm
       */
      timerange_end?: string | null
      /**
       * Who needs to be included in the meeting - list of email addresses. Do not include Sid (sid.mathur@gmail.com)
       */
      participants?: string | null
      /**
       * Who are the EAs and for who - email address of EA (email address of participant). Do not include Ashley (ashley.sidsai@gmail.com)
       */
      executive_assistants?: string | null
      /**
       * Who are the silent observers - list of email addresses. 
       */
      silent_observers?: string | null
      /**
       * Any additional context for the meeting
       */
      other_context?: string | null
      /**
       * Date of the request
       */
      date_of_request?: string | null
    }
}