/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum RequestType {
  DoesTimeWork = "DoesTimeWork",
  SuggestTime = "SuggestTime",
  BookTime = "BookTime",
}

export interface CalendarIntent {
  /**
   * Whether this message requires a calendar action
   */
  action_needed: boolean
  /**
   * Type of calendar request
   */
  request_type: RequestType
  /**
   * Name of person who originally requested the meeting
   */
  requestor: string
  /**
   * What time slots are suggested
   */
  time_slots_requested: string
  /**
   * How long is being requested (e.g., "30 mins", "1 hour", "2 hours")
   */
  meeting_duration: string
  /**
   * The earliest datetime being considered for the meeting formatted as YYYY-mm-dd hh:mm
   */
  timerange_start: string
  /**
   * The latest datetime being considered for the meeting formatted as YYYY-mm-dd hh:mm
   */
  timerange_end: string
  /**
   * Who needs to be included in the meeting - list of email addresses. Do not include Sid (sid.mathur@gmail.com)
   */
  participants: string
  /**
   * Who are the EAs and for who - email address of EA (email address of participant). Do not include Ashley (ashley.sidsai@gmail.com)
   */
  executive_assistants: string
  /**
   * Any additional context for the meeting
   */
  other_context: string
  /**
   * Date of the request
   */
  date_of_request: string
  
}
