name: Implementation PR Guard
on:
  push:
    branches: [ 'feature/**' ]  
    paths-ignore: [ 'docs/**' ]
permissions:
  pull-requests: read
  contents: read
  checks: write
jobs:
  guard:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Implementation PR Guard
        run: |
          chmod +x scripts/ensure-tests-present.sh
          ./scripts/ensure-tests-present.sh