name: RFC PR from feature branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Feature branch name (e.g., feature/123-my-feature)'
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  rfc-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue number from branch name
        id: extract
        run: |
          BRANCH_NAME="${{ github.event.inputs.branch_name }}"
          ISSUE_NUMBER=$(echo "$BRANCH_NAME" | sed -E 's#^feature/([0-9]+)-.*#\1#')
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          echo "Extracted issue number: $ISSUE_NUMBER from branch: $BRANCH_NAME"

      - name: Create RFC PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.extract.outputs.branch_name }}
          ISSUE_NUMBER: ${{ steps.extract.outputs.issue_number }}
        run: |
          # Check if PR already exists
          if gh pr list --repo mathursrus/Ashley-Calendar-AI --head "$BRANCH_NAME" --json number | grep -q "number"; then
            echo "✅ PR already exists for branch $BRANCH_NAME"
            gh pr list --repo mathursrus/Ashley-Calendar-AI --head "$BRANCH_NAME" --json number,title,url
          else
            # Create new PR using GitHub CLI
            echo "Creating RFC PR for branch $BRANCH_NAME"
            
            # Note: This will still fail due to GitHub Actions restrictions
            # but provides clear error message and instructions
            echo "⚠️  GitHub Actions cannot create PRs automatically due to security restrictions."
            echo "Please create the RFC PR manually using:"
            echo ""
            echo "gh pr create \\"
            echo "  --repo mathursrus/Ashley-Calendar-AI \\"
            echo "  --title \"RFC: Issue #$ISSUE_NUMBER\" \\"
            echo "  --body \"Linked issue: #$ISSUE_NUMBER\" \\"
            echo "  --base master \\"
            echo "  --head \"$BRANCH_NAME\" \\"
            echo "  --label \"type:design,needs:review\""
            echo ""
            echo "Or visit: https://github.com/mathursrus/Ashley-Calendar-AI/compare/master...$BRANCH_NAME"
            
            # Attempt automatic creation (will fail but shows the limitation)
            gh pr create \
              --repo mathursrus/Ashley-Calendar-AI \
              --title "RFC: Issue #$ISSUE_NUMBER" \
              --body "Linked issue: #$ISSUE_NUMBER" \
              --base master \
              --head "$BRANCH_NAME" \
              --label "type:design,needs:review" || {
                echo ""
                echo "❌ Automatic PR creation failed due to GitHub Actions security restrictions."
                echo "✅ Use the manual command above or the GitHub UI link provided."
                exit 0  # Don't fail the workflow
              }
          fi

      - name: Add issue comment with PR instructions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.extract.outputs.issue_number }}
          BRANCH_NAME: ${{ steps.extract.outputs.branch_name }}
        run: |
          # Check if PR exists first
          if gh pr list --repo mathursrus/Ashley-Calendar-AI --head "$BRANCH_NAME" --json number | grep -q "number"; then
            echo "PR already exists, skipping comment"
          else
            # Add helpful comment to the issue
            gh issue comment $ISSUE_NUMBER --repo mathursrus/Ashley-Calendar-AI --body "
          ## 🚀 Ready to Create RFC PR
          
          Your feature branch \`$BRANCH_NAME\` is ready for RFC PR creation.
          
          **Quick Create:**
          \`\`\`bash
          gh pr create --repo mathursrus/Ashley-Calendar-AI --title \"RFC: Issue #$ISSUE_NUMBER\" --body \"Linked issue: #$ISSUE_NUMBER\" --base master --head \"$BRANCH_NAME\" --label \"type:design,needs:review\"
          \`\`\`
          
          **Or use GitHub UI:** [Create PR](https://github.com/mathursrus/Ashley-Calendar-AI/compare/master...$BRANCH_NAME)
          
          ---
          *This comment was generated by the RFC PR workflow. The workflow cannot create PRs automatically due to GitHub Actions security restrictions.*
          "
          fi