name: RFC PR from feature branch
on:
  push:
    branches: ['feature/**']
    paths: ['docs/rfcs/**']
permissions:
  contents: write
  pull-requests: write
jobs:
  rfc-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          ref: master
      - name: Checkout feature branch
        run: |
          git checkout ${{ github.ref_name }}
      - name: Derive issue number from branch
        id: vars
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME}"
          ISSUE_NUMBER=$(echo "$BRANCH_NAME" | sed -E 's#^feature/([0-9]+)-.*#\1#')
          echo "issue=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
      - name: Open/Update RFC PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
          ISSUE_NUMBER: ${{ steps.vars.outputs.issue }}
        run: |
          # Check if PR already exists
          if gh pr view "$BRANCH_NAME" --json number > /dev/null 2>&1; then
            echo "PR already exists for branch $BRANCH_NAME"
          else
            # Create new PR
            gh pr create \
              --title "RFC: $BRANCH_NAME" \
              --body "Linked issue: #$ISSUE_NUMBER" \
              --base master \
              --head "$BRANCH_NAME" \
              --label "type:design,needs:review"
            echo "Created RFC PR for branch $BRANCH_NAME"
          fi