name: Test Plan PR from feature branch
on:
  push:
    branches: ['feature/**']
    paths: ['docs/testplans/**']
permissions:
  contents: write
  pull-requests: write
jobs:
  testplan-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          ref: master
      - name: Checkout feature branch
        run: |
          git checkout ${{ github.ref_name }}
      - name: Derive issue number from branch
        id: vars
        run: echo "issue=$(echo '${GITHUB_REF_NAME#refs/heads/}' | sed -E 's#^feature/([0-9]+)-.*#\1#')" >> $GITHUB_OUTPUT
      - name: Open/Update Test Plan PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
          ISSUE_NUMBER: ${{ steps.vars.outputs.issue }}
        run: |
          # Check if PR already exists
          if gh pr view "$BRANCH_NAME" --json number > /dev/null 2>&1; then
            echo "PR already exists for branch $BRANCH_NAME"
          else
            # Create new PR
            gh pr create \
              --title "Test Plan: $BRANCH_NAME" \
              --body "Linked issue: #$ISSUE_NUMBER" \
              --base master \
              --head "$BRANCH_NAME" \
              --label "type:test-plan,needs:review"
            echo "Created Test Plan PR for branch $BRANCH_NAME"
          fi